### ISSUE TITLE
Colour-up Core Repo

### ISSUE THREAD

**Issue by Thaanu2001** [Satriaana/Blog#26]
Add any touchups for [core repo](https://github.com/Satriaana/Core)

- [x] Need a description from @Satriaana/blog-team
- [x] Colour-up the repo @Satriaana/design-team

**Comment by ChamodiePubudini** [comment]
SATRIAANA is a community which is an independent and having a  greater focus on privacy
 level as an open source community. We are maintaining our  targets accurately in order to provide a meaningful output to the global citizen .

Blog team has provided the necessary content. The rest belongs to the @Satriaana/design-team
